#!/usr/bin/env node
/**
 * Generate public/config.js with the OpenWeather API key from env.
 * Falls back to placeholder to avoid committing secrets.
 */
const fs = require('fs');
const path = require('path');

const key = process.env.REACT_APP_OPENWEATHER_API_KEY || 'YOUR_API_KEY';
const outPath = path.join(__dirname, '..', 'public', 'config.js');

const contents = `// Auto-generated by scripts/generate-config.js
// Replace with a valid OpenWeather API key at build time.
window.__OPENWEATHER_API_KEY__ = '${key}';
`;

fs.writeFileSync(outPath, contents, 'utf8');
console.log(`Generated public/config.js with key=${key === 'YOUR_API_KEY' ? 'placeholder' : 'provided value'}`);
